# Generated by Django 2.2.5 on 2019-10-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0004_appointmenttimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
