# Generated by Django 2.2.5 on 2019-10-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0006_auto_20191023_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='num',
            field=models.CharField(default=0.0, max_length=1),
        ),
    ]
