# Generated by Django 2.2.5 on 2019-10-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0007_appointment_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
